### ISSUE TITLE
CA_LOG_SUCCESS_TO_DB does nothing.

### ISSUE THREAD

**Issue by olanystrom** [Solar-Helix-Independent-Transport/allianceauth-celeryanalytics#7]
According to README.md
set CA_LOG_SUCCESS_TO_DB If you don't want the module to log Successful Tasks to database, set this to False. Default is True

According to the code setting CA_LOG_SUCCESS_TO_DB in local.py does nothing.
And if i set CA_LOG_TO_DB to false then nothing is logged.

https://github.com/Solar-Helix-Independent-Transport/allianceauth-celeryanalytics/blob/9e2854aabff842d605d87f3748a8737de6c38f97/celeryanalytics/app_settings.py#L5

How is this supposed to work ?

**Comment by pvyParts** [comment]
rofl... good pickup. I'll patch it now

**Comment by pvyParts** [comment]
fixed in 0.0.6
